### ISSUE TITLE
does this need to be its own repo?

### ISSUE THREAD

**Issue by jessieay** [18F/dev-environment-standardization#1]
What about having it as a set of pages within https://github.com/18F/development-guide/blob/18f-pages/pages/project-setup.md ?

**Comment by mbland** [comment]
We're just getting started with this guide, but have generated a substantial amount of material for it (on the internal "Doc WG > Dev Environment Standardization Drafts" Google Drive) and are considering having it stand as something generally applicable outside of 18F. So maybe one day, but not yet.

**Comment by kaitlin** [comment]
In general, I get the sense these are targeted towards the broad federal space (agencies + contractors). If that's true, I wonder if there's something we can do with the branding/info architecture of all these guides to make it more explicit?

**Comment by mbland** [comment]
Yeah, that's the dream. @coreycaitlin has started taking a stab at guides info architecture in the Doc WG; @emileighoutlaw and the content folks are mulling it over as well.

**Comment by kaitlin** [comment]
So what you're saying is... 

![](https://media.giphy.com/media/TlxzGhfErTp5K/giphy.gif)

**Comment by coreycaitlin** [comment]
The difference in audiences between guides certainly seems like a key thing to communicate somehow. Still trying to wrap my head around it, and will definitely have more questions soon.

**Comment by jessieay** [comment]
Thanks for the explanations, all! 

![thank_you](https://cloud.githubusercontent.com/assets/601515/11249946/cde64404-8dde-11e5-8dc0-4cbb2a9ca1c0.gif)

Closing this issue now
